config/routes.rb
AjaxProject3::Application.routes.draw do
  resources :users
  match '/signup', :to => 'users#new'
  match 'contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  user_id    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :user_id, :password, :password_confirmation
  
  validates :user_id, :presence => true,
                      :length => { :maximum => 500 },
                      :uniqueness => { :case_sensitive => false }
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..500 }
  
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(user_id, submitted_password)
    user = find_by_user_id(user_id)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.user_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
      logo = image_tag("icon.png", :alt => "AJAX Project 3", :class => "round")
  end
  
  # Return on a per-page basis
  def title
    base_title = "AJAX Project 3"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>

<!--[if lt IE 8[>
  <%= stylesheet_link_tag 'blueprint/ie' %>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <section class="round">
      <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About AJAX Project 3</h1>
<p>This is the third project for the AJAX class I am taking in the Spring 2012 semester.  Here is the assignment:</p>
<p>
  Using any server-side language,
  You should create a database named blog*<br />
  Generate the database and table structure for the project <br /><br /><br />
      DATABASE: `blog` ;<br />
        TABLE: blog.users<br />
               `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,<br />
               `user_id` VARCHAR( 500 ) NOT NULL ,<br />
               `password` VARCHAR( 500 ) NOT NULL ,<br />
               `created` DATETIME NOT NULL<br />
               <br />
        TABLE: blog.posts<br />
               `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,<br />
               `user_id` VARCHAR( 500 ) NOT NULL ,<br />
               `title` VARCHAR( 500 ) NOT NULL ,<br />
              `description` VARCHAR( 500 ) NOT NULL ,`created` DATETIME NOT NULL<br />
        <br />
        TABLE: blog.comments <br />      
               `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,<br />
               `user_id` VARCHAR( 500 ) NOT NULL ,<br />
               `post_id` INT NOT NULL ,<br />
               `description` VARCHAR ( 500 ) ,<br />
               `created` DATETIME NOT NULL<br />
  <ul>
    <li>create a login page that authenticates users against the users table - if the user is valid, allow the user to navigate to a page that displays all posts and their related comments. Otherwise, if the user is invalid display an error message.</li>
    <li>the blog posts page should meet the following criteria</li>
    <ul>
      <li>there can be no submits. all server interaction must be done using ajax</li>
      <li>display all posts (just the description) </li>
      <li>allow entry of a new post - the post should get saved to the posts table and should update the user-interface (it should be added to the list of all posts)</li>
      <li>allow any post in the list of all posts to be deleted (only if the currently logged in user created the post) - it should be removed from the db and from the user-interface. The delete process should NOT remove the corresponding comments.</li>
      <li>allow the user to comment on any post - the comment should get saved to the comments table and update the user interface (it should appear next to the related post)</li>
      <li>all comments that originated from the currently logged in user should be highlighted (ex. a different background color) from posts by other users</li>
    </ul>
  </ul>
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Want to see more?  Check out my site,<a href="http://www.andreajessup.com">www.andreajessup.com</a></p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>I can <i>try</i> to help :)</p>

app/views/pages/home.html.erb
<h1>AJAX Project 3</h1>
<p>This is the home page for my project</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.user_id %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>User ID:</strong> <%= @user.user_id %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>